### ISSUE TITLE
No context available when using express-session with Memory store

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback-context#6]
If using session and token middleware, trying to access the explorer crashes the server with a "Error: No context available. ns.run() or ns.bind() must be called first."

see also strongloop/loopback#2636 and https://github.com/azatoth/loopback-sandbox for a testcase (is also reproducible if using plain loopback-context 1.0.0 without the cls-hooked patch)

@bajtos

**Comment by azatoth** [comment]
As loopback is not using getCurrentContext() anymore but is accessing the raw loopbackContext object, there is no check if the context is active or not.

**Comment by bajtos** [comment]
So apparently the `getCurrentContext` checks for `ns.active` too. The patch https://github.com/strongloop/loopback/pull/2604 which inlined `getCurrentContext` did not include this check.

**Comment by bajtos** [comment]
The problem is caused by the memory store provided by express-session, which calls `setImmediate` to defer callbacks - see [session/memory.js#L25-L27](https://github.com/expressjs/session/blob/bf359988222c8919cc4234bb72e1c00985a69042/session/memory.js#L25-L27). Apparently `setImmediate` is not supported by node-continuation-local-storage. 

I agree loopback apps should not crash in such case, https://github.com/strongloop/loopback/pull/2649 will fix that.

However, fixing express-session is up to somebody else to do.

**Comment by bajtos** [comment]
> The problem is caused by the memory store provided by express-session, which calls setImmediate to defer callbacks - see session/memory.js#L25-L27. Apparently setImmediate is not supported by node-continuation-local-storage.

Let me clarify this. When I changed `session/memory` to use `process.nextTick` instead of `setImmediate`, then the app started to work. There may be something else in play, because node-continuation-local-storage claims to support `setImmediate` according to their docs (https://github.com/othiym23/node-continuation-local-storage#continuation-local-storage).

**Comment by Jeff-Lewis** [comment]
@bajtos have you had a chance to try cls-hooked? I'm curious if it helps with some of these known cls issues. The latest cls-hooked version supports node 4.5.0.

**Comment by azatoth** [comment]
@Jeff-Lewis initially I was testing with cls-hooked enabled (see https://github.com/azatoth/loopback-sandbox)

**Comment by bajtos** [comment]
@Jeff-Lewis there is a pending pull request reworking loopback-context to use cls-hooked, see https://github.com/strongloop/loopback-context/pull/2

**Comment by josieusa** [comment]
`cls-hooked` depends on `async-hook`, which may support`setImmediate`, or at least so it seems from the source code. See https://github.com/AndreasMadsen/async-hook/blob/9c2d1ee927233ec1ad31cbf286029c1c98bd9885/patches/timers.js#L16

**Comment by josieusa** [comment]
Link to PR #11

**Comment by josieusa** [comment]
`express-session` is known to have problems with `cls-hooked`, see othiym23/node-continuation-local-storage#29. Maybe I could add tests for `express-session` to PR #19 to see if it solves the issue.
